export class ZendeskArticle {
  id: number;
  url: string;
  htmlUrl: string;
  authorId: number;
  commentsDisabled: boolean;
  draft: boolean;
  promoted: boolean;
  position: number;
  voteSum: number;
  voteCount: number;
  sectionId: number;
  createdAt: string;
  updatedAt: string;
  name: string;
  title: string;
  sourceLocale: string;
  locale: string;
  outdated: boolean;
  outdatedLocales: string[];
  editedAt: string;
  userSegmentId?: number;
  permissionGroupId: number;
  contentTagIds: (number | string)[];
  labelNames: string[];
  body: string;

  constructor(data: {
    id?: number;
    url?: string;
    html_url?: string;
    author_id?: number;
    comments_disabled?: boolean;
    draft?: boolean;
    promoted?: boolean;
    position?: number;
    vote_sum?: number;
    vote_count?: number;
    section_id?: number;
    created_at?: string;
    updated_at?: string;
    name?: string;
    title?: string;
    source_locale?: string;
    locale?: string;
    outdated?: boolean;
    outdated_locales?: string[];
    edited_at?: string;
    user_segment_id?: number;
    permission_group_id?: number;
    content_tag_ids?: (number | string)[];
    label_names?: string[];
    body?: string;
  }) {
    this.id = data.id!;
    this.url = data.url!;
    this.htmlUrl = data.html_url!;
    this.authorId = data.author_id!;
    this.commentsDisabled = data.comments_disabled!;
    this.draft = data.draft!;
    this.promoted = data.promoted!;
    this.position = data.position!;
    this.voteSum = data.vote_sum!;
    this.voteCount = data.vote_count!;
    this.sectionId = data.section_id!;
    this.createdAt = data.created_at!;
    this.updatedAt = data.updated_at!;
    this.name = data.name!;
    this.title = data.title!;
    this.sourceLocale = data.source_locale!;
    this.locale = data.locale!;
    this.outdated = data.outdated!;
    this.outdatedLocales = data.outdated_locales!;
    this.editedAt = data.edited_at!;
    this.userSegmentId = data.user_segment_id;
    this.permissionGroupId = data.permission_group_id!;
    this.contentTagIds = data.content_tag_ids!;
    this.labelNames = data.label_names!;
    this.body = data.body!;
  }
}
